### ISSUE TITLE
Pagination

### ISSUE THREAD

**Issue by cohix** [diggerino/digio-api#3]
Some endpoints like the images/list endpoint are paginated, and therefore all the results are not returned. Is there a way you could enable pagination, or alternatively a generic "get" function that allows us to enter a custom api endpoint?

ex:

```
api.get("images/list?page=3", function(err, data)
{
    if(!err) console.log(data);
} 
```

**Comment by mythern** [comment]
Looking into it now. We are adhering to the format we have used for the other api methods, so a generic get method will not be implemented. Instead a series of arguments can be passed to the api.images.list and other list methods to apply pagination as well as the new filters available in the APIv2.

**Comment by myth** [comment]
Just a heads up, after some consideration and new additions to the API, we have decided to perform some changes breaking backwards compatibility. Now that I have some spare time soon, I will be changing the behaviour of all endpoint methods in the API library.

The gist of what the new approach will look like is `api.droplets.list().do()`.
A wrapper object will contain some extra settings for the request, like pagination, additional filters for some of the endpoints etc.

Adding pagination would look like `api.droplets.list().page(3).per_page(50).do()`, and the command is only executed after the `do()` is called. This will allow reducing the amount of parameters in the methods to only the required ones. All filters, paginations, and optionals will be converted to methods that allow chaining.
